openapi: 3.0.0
info:
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/)
    or HTML.
  title: Sample API
  version: 0.1.9
servers:
- description: Optional server description, e.g. Main (production) server
  url: http://localhost:8080/myapp/
- description: Optional server description, e.g. Internal staging server for testing
  url: http://staging-api.example.com
paths:
  /users:
    get:
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: A JSON array of user names
      summary: Returns a list of users.
      x-accepts: application/json
  /users/{userId}:
    get:
      parameters:
      - description: The ID of the user to return.
        explode: false
        in: path
        name: userId
        required: true
        schema:
          format: int64
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: A user object.
        "400":
          description: The specified user ID is invalid (not a number).
        "404":
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
      summary: Returns a user by ID.
      x-accepts: application/json
  /files:
    get:
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: A JSON array of file names
      summary: Returns a list of files.
      x-accepts: application/json
  /files/download/{fileId}:
    get:
      operationId: download
      parameters:
      - description: The ID of the download file to return.
        explode: false
        in: path
        name: fileId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: OK
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Error
      x-accepts: application/json
components:
  schemas:
    inline_response_200:
      example:
        name: Jessica Smith
        id: 4
      properties:
        id:
          example: 4
          format: int64
          type: integer
        name:
          example: Jessica Smith
          type: string
      type: object
