"""
    Sample API

    Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.  # noqa: E501

    The version of the OpenAPI document: 0.1.9
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_get(self):
        """Test case for users_get

        Returns a list of users.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
